var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa={},ba;for(ba in g)g.hasOwnProperty(ba)&&(aa[ba]=g[ba]);var ca=[],da="./this.program";function ea(a,b){throw b;}var fa=!1,ha=!1,ia=!1,ja=!1,ka=!1;fa="object"===typeof window;ha="function"===typeof importScripts;ia=(ja="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node)&&!fa&&!ha;ka=!fa&&!ia&&!ha;var h="",la,ma,na,oa;
if(ia)h=__dirname+"/",la=function(a,b){na||(na=require("fs"));oa||(oa=require("path"));a=oa.normalize(a);return na.readFileSync(a,b?null:"utf8")},ma=function(a){a=la(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a},1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/")),ca=process.argv.slice(2),"undefined"!==typeof module&&(module.exports=g),process.on("uncaughtException",function(a){if(!(a instanceof pa))throw a;}),process.on("unhandledRejection",l),ea=function(a){process.exit(a)},
g.inspect=function(){return"[Emscripten Module object]"};else if(ka)"undefined"!=typeof read&&(la=function(a){return read(a)}),ma=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?ca=scriptArgs:"undefined"!=typeof arguments&&(ca=arguments),"function"===typeof quit&&(ea=function(a){quit(a)}),"undefined"!==typeof print&&("undefined"===typeof console&&(console={}),console.log=print,
console.warn=console.error="undefined"!==typeof printErr?printErr:print);else if(fa||ha)ha?h=self.location.href:document.currentScript&&(h=document.currentScript.src),h=0!==h.indexOf("blob:")?h.substr(0,h.lastIndexOf("/")+1):"",la=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},ha&&(ma=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
var qa=g.print||console.log.bind(console),m=g.printErr||console.warn.bind(console);for(ba in aa)aa.hasOwnProperty(ba)&&(g[ba]=aa[ba]);aa=null;g.arguments&&(ca=g.arguments);g.thisProgram&&(da=g.thisProgram);g.quit&&(ea=g.quit);var ra;g.wasmBinary&&(ra=g.wasmBinary);var sa;g.noExitRuntime&&(sa=g.noExitRuntime);"object"!==typeof WebAssembly&&m("no native wasm support detected");var ta,ua=new WebAssembly.Table({initial:65,maximum:65,element:"anyfunc"}),va=!1;
function assert(a,b){a||l("Assertion failed: "+b)}function wa(a){var b=g["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function xa(a,b,c,d){var e={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=ya(c);q(a,u,b,c)}return b},array:function(a){var b=ya(a.length);v.set(a,b);return b}},f=wa(a),k=[];a=0;if(d)for(var n=0;n<d.length;n++){var p=e[c[n]];p?(0===a&&(a=za()),k[n]=p(d[n])):k[n]=d[n]}c=f.apply(null,k);c=function(a){return"string"===b?w(a):"boolean"===b?!!a:a}(c);0!==a&&Aa(a);return c}var Ba="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ca(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&Ba)return Ba.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var k=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|k:(e&7)<<18|f<<12|k<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function w(a,b){return a?Ca(u,a,b):""}
function q(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var k=a.charCodeAt(f);if(55296<=k&&57343>=k){var n=a.charCodeAt(++f);k=65536+((k&1023)<<10)|n&1023}if(127>=k){if(c>=d)break;b[c++]=k}else{if(2047>=k){if(c+1>=d)break;b[c++]=192|k>>6}else{if(65535>=k){if(c+2>=d)break;b[c++]=224|k>>12}else{if(c+3>=d)break;b[c++]=240|k>>18;b[c++]=128|k>>12&63}b[c++]=128|k>>6&63}b[c++]=128|k&63}}b[c]=0;return c-e}
function Da(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");function Ea(a){var b=Da(a)+1,c=ya(b);q(a,v,c,b);return c}function Fa(a){0<a%65536&&(a+=65536-a%65536);return a}var buffer,v,u,Ga,Ha,x,Ia,y,A;
function Ja(a){buffer=a;g.HEAP8=v=new Int8Array(a);g.HEAP16=Ga=new Int16Array(a);g.HEAP32=x=new Int32Array(a);g.HEAPU8=u=new Uint8Array(a);g.HEAPU16=Ha=new Uint16Array(a);g.HEAPU32=Ia=new Uint32Array(a);g.HEAPF32=y=new Float32Array(a);g.HEAPF64=A=new Float64Array(a)}var Ka=g.TOTAL_MEMORY||67108864;g.wasmMemory?ta=g.wasmMemory:ta=new WebAssembly.Memory({initial:Ka/65536});ta&&(buffer=ta.buffer);Ka=buffer.byteLength;Ja(buffer);x[1711768]=12090112;
function La(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.bd;"number"===typeof c?void 0===b.Dc?g.dynCall_v(c):g.dynCall_vi(c,b.Dc):c(void 0===b.Dc?null:b.Dc)}}}var Ma=[],Na=[],Oa=[],Pa=[],Qa=[],Ra=!1;function Sa(){var a=g.preRun.shift();Ma.unshift(a)}var Ta=Math.abs,Ua=Math.ceil,Va=Math.floor,Wa=Math.min,Xa=0,Ya=null,Za=null;function $a(){Xa++;g.monitorRunDependencies&&g.monitorRunDependencies(Xa)}
function ab(){Xa--;g.monitorRunDependencies&&g.monitorRunDependencies(Xa);if(0==Xa&&(null!==Ya&&(clearInterval(Ya),Ya=null),Za)){var a=Za;Za=null;a()}}g.preloadedImages={};g.preloadedAudios={};function l(a){if(g.onAbort)g.onAbort(a);qa(a);m(a);va=!0;throw new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");}
function bb(){var a=cb;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var cb="atom-ui.wasm";if(!bb()){var db=cb;cb=g.locateFile?g.locateFile(db,h):h+db}function eb(){try{if(ra)return new Uint8Array(ra);if(ma)return ma(cb);throw"both async and sync fetching of the wasm failed";}catch(a){l(a)}}
function fb(){return ra||!fa&&!ha||"function"!==typeof fetch?new Promise(function(a){a(eb())}):fetch(cb,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+cb+"'";return a.arrayBuffer()}).catch(function(){return eb()})}var B,C;Na.push({bd:function(){gb()}});function hb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}
function E(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=hb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}function ib(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function jb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}
function kb(a){g.___errno_location&&(x[g.___errno_location()>>2]=a)}function lb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:mb;if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=hb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var nb=[];function ob(a,b){nb[a]={input:[],output:[],wc:b};pb(a,qb)}
var qb={open:function(a){var b=nb[a.node.rdev];if(!b)throw new F(43);a.tty=b;a.seekable=!1},close:function(a){a.tty.wc.flush(a.tty)},flush:function(a){a.tty.wc.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.wc.Pc)throw new F(60);for(var e=0,f=0;f<d;f++){try{var k=a.tty.wc.Pc(a.tty)}catch(n){throw new F(29);}if(void 0===k&&0===e)throw new F(6);if(null===k||void 0===k)break;e++;b[c+f]=k}e&&(a.node.timestamp=Date.now());return e},write:function(a,b,c,d){if(!a.tty||!a.tty.wc.Gc)throw new F(60);
try{for(var e=0;e<d;e++)a.tty.wc.Gc(a.tty,b[c+e])}catch(f){throw new F(29);}d&&(a.node.timestamp=Date.now());return e}},sb={Pc:function(a){if(!a.input.length){var b=null;if(ia){var c=Buffer.Yc?Buffer.Yc(256):new Buffer(256),d=0;try{d=na.readSync(process.stdin.fd,c,0,256,null)}catch(e){if(-1!=e.toString().indexOf("EOF"))d=0;else throw e;}0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==
typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=rb(b)}return a.input.shift()},Gc:function(a,b){null===b||10===b?(qa(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(qa(Ca(a.output,0)),a.output=[])}},tb={Gc:function(a,b){null===b||10===b?(m(Ca(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(m(Ca(a.output,0)),a.output=[])}},G={kc:null,mc:function(){return G.createNode(null,
"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new F(63);G.kc||(G.kc={dir:{node:{jc:G.cc.jc,ic:G.cc.ic,lookup:G.cc.lookup,Bc:G.cc.Bc,rename:G.cc.rename,unlink:G.cc.unlink,rmdir:G.cc.rmdir,readdir:G.cc.readdir,symlink:G.cc.symlink},stream:{pc:G.dc.pc}},file:{node:{jc:G.cc.jc,ic:G.cc.ic},stream:{pc:G.dc.pc,read:G.dc.read,write:G.dc.write,Ic:G.dc.Ic,Sc:G.dc.Sc,Uc:G.dc.Uc}},link:{node:{jc:G.cc.jc,ic:G.cc.ic,readlink:G.cc.readlink},stream:{}},Lc:{node:{jc:G.cc.jc,
ic:G.cc.ic},stream:ub}});c=vb(a,b,c,d);H(c.mode)?(c.cc=G.kc.dir.node,c.dc=G.kc.dir.stream,c.bc={}):32768===(c.mode&61440)?(c.cc=G.kc.file.node,c.dc=G.kc.file.stream,c.ec=0,c.bc=null):40960===(c.mode&61440)?(c.cc=G.kc.link.node,c.dc=G.kc.link.stream):8192===(c.mode&61440)&&(c.cc=G.kc.Lc.node,c.dc=G.kc.Lc.stream);c.timestamp=Date.now();a&&(a.bc[b]=c);return c},vd:function(a){if(a.bc&&a.bc.subarray){for(var b=[],c=0;c<a.ec;++c)b.push(a.bc[c]);return b}return a.bc},wd:function(a){return a.bc?a.bc.subarray?
a.bc.subarray(0,a.ec):new Uint8Array(a.bc):new Uint8Array},Nc:function(a,b){var c=a.bc?a.bc.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.bc,a.bc=new Uint8Array(b),0<a.ec&&a.bc.set(c.subarray(0,a.ec),0))},ld:function(a,b){if(a.ec!=b)if(0==b)a.bc=null,a.ec=0;else{if(!a.bc||a.bc.subarray){var c=a.bc;a.bc=new Uint8Array(new ArrayBuffer(b));c&&a.bc.set(c.subarray(0,Math.min(b,a.ec)))}else if(a.bc||(a.bc=[]),a.bc.length>b)a.bc.length=b;else for(;a.bc.length<b;)a.bc.push(0);
a.ec=b}},cc:{jc:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;H(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.ec:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Zc=4096;b.blocks=Math.ceil(b.size/b.Zc);return b},ic:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&
G.ld(a,b.size)},lookup:function(){throw wb[44];},Bc:function(a,b,c,d){return G.createNode(a,b,c,d)},rename:function(a,b,c){if(H(a.mode)){try{var d=xb(b,c)}catch(f){}if(d)for(var e in d.bc)throw new F(55);}delete a.parent.bc[a.name];a.name=c;b.bc[c]=a;a.parent=b},unlink:function(a,b){delete a.bc[b]},rmdir:function(a,b){var c=xb(a,b),d;for(d in c.bc)throw new F(55);delete a.bc[b]},readdir:function(a){var b=[".",".."],c;for(c in a.bc)a.bc.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=
G.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new F(28);return a.link}},dc:{read:function(a,b,c,d,e){var f=a.node.bc;if(e>=a.node.ec)return 0;a=Math.min(a.node.ec-e,d);if(8<a&&f.subarray)b.set(f.subarray(e,e+a),c);else for(d=0;d<a;d++)b[c+d]=f[e+d];return a},write:function(a,b,c,d,e,f){b.buffer===v.buffer&&(f=!1);if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.bc||a.bc.subarray)){if(f)return a.bc=b.subarray(c,c+d),a.ec=d;if(0===
a.ec&&0===e)return a.bc=new Uint8Array(b.subarray(c,c+d)),a.ec=d;if(e+d<=a.ec)return a.bc.set(b.subarray(c,c+d),e),d}G.Nc(a,e+d);if(a.bc.subarray&&b.subarray)a.bc.set(b.subarray(c,c+d),e);else for(f=0;f<d;f++)a.bc[e+f]=b[c+f];a.ec=Math.max(a.ec,e+d);return d},pc:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.ec);if(0>b)throw new F(28);return b},Ic:function(a,b,c){G.Nc(a.node,b+c);a.node.ec=Math.max(a.node.ec,b+c)},Sc:function(a,b,c,d,e,f,k){if(32768!==(a.node.mode&
61440))throw new F(43);c=a.node.bc;if(k&2||c.buffer!==b.buffer){if(0<e||e+d<a.node.ec)c.subarray?c=c.subarray(e,e+d):c=Array.prototype.slice.call(c,e,e+d);a=!0;e=b.buffer==v.buffer;d=K(d);if(!d)throw new F(48);(e?v:b).set(c,d)}else a=!1,d=c.byteOffset;return{Bd:d,qd:a}},Uc:function(a,b,c,d,e){if(32768!==(a.node.mode&61440))throw new F(43);if(e&2)return 0;G.dc.write(a,b,0,d,c,!1);return 0}}},yb=null,zb={},Ab=[],Cb=1,Db=null,mb="/",Eb=!0,L={},F=null,wb={};
function M(a,b){a=lb(mb,a);b=b||{};if(!a)return{path:"",node:null};var c={Oc:!0,Hc:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.Hc)throw new F(32);a=hb(a.split("/").filter(function(a){return!!a}),!1);var e=yb;c="/";for(d=0;d<a.length;d++){var f=d===a.length-1;if(f&&b.parent)break;e=xb(e,a[d]);c=E(c+"/"+a[d]);e.uc&&(!f||f&&b.Oc)&&(e=e.uc.root);if(!f||b.sc)for(f=0;40960===(e.mode&61440);)if(e=Fb(c),c=lb(ib(c),e),e=M(c,{Hc:b.Hc}).node,40<f++)throw new F(32);}return{path:c,node:e}}
function N(a){for(var b;;){if(a===a.parent)return a=a.mc.Tc,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Gb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%Db.length}function Hb(a){var b=Gb(a.parent.id,a.name);a.vc=Db[b];Db[b]=a}function Ib(a){var b=Gb(a.parent.id,a.name);if(Db[b]===a)Db[b]=a.vc;else for(b=Db[b];b;){if(b.vc===a){b.vc=a.vc;break}b=b.vc}}
function xb(a,b){var c;if(c=(c=Jb(a,"x"))?c:a.cc.lookup?0:2)throw new F(c,a);for(c=Db[Gb(a.id,b)];c;c=c.vc){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.cc.lookup(a,b)}
function vb(a,b,c,d){Kb||(Kb=function(a,b,c,d){a||(a=this);this.parent=a;this.mc=a.mc;this.uc=null;this.id=Cb++;this.name=b;this.mode=c;this.cc={};this.dc={};this.rdev=d},Kb.prototype={},Object.defineProperties(Kb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},gd:{get:function(){return H(this.mode)}},ed:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Kb(a,b,c,d);Hb(a);return a}function H(a){return 16384===(a&61440)}var Lb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Mb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Jb(a,b){if(Eb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 2}else return 2;return 0}
function Nb(a,b){try{return xb(a,b),20}catch(c){}return Jb(a,"wx")}function Ob(a,b,c){try{var d=xb(a,b)}catch(e){return e.fc}if(a=Jb(a,"wx"))return a;if(c){if(!H(d.mode))return 54;if(d===d.parent||N(d)===mb)return 10}else if(H(d.mode))return 31;return 0}function Pb(a){var b=4096;for(a=a||0;a<=b;a++)if(!Ab[a])return a;throw new F(33);}
function Qb(a,b){Rb||(Rb=function(){},Rb.prototype={},Object.defineProperties(Rb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Rb,d;for(d in a)c[d]=a[d];a=c;b=Pb(b);a.fd=b;return Ab[b]=a}var ub={open:function(a){a.dc=zb[a.node.rdev].dc;a.dc.open&&a.dc.open(a)},pc:function(){throw new F(70);}};function pb(a,b){zb[a]={dc:b}}
function Sb(a,b){var c="/"===b,d=!b;if(c&&yb)throw new F(10);if(!c&&!d){var e=M(b,{Oc:!1});b=e.path;e=e.node;if(e.uc)throw new F(10);if(!H(e.mode))throw new F(54);}b={type:a,zd:{},Tc:b,jd:[]};a=a.mc(b);a.mc=b;b.root=a;c?yb=a:e&&(e.uc=b,e.mc&&e.mc.jd.push(b))}function Tb(a,b,c){var d=M(a,{parent:!0}).node;a=jb(a);if(!a||"."===a||".."===a)throw new F(28);var e=Nb(d,a);if(e)throw new F(e);if(!d.cc.Bc)throw new F(63);return d.cc.Bc(d,a,b,c)}
function O(a,b){return Tb(a,(void 0!==b?b:511)&1023|16384,0)}function Ub(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Tb(a,b|8192,c)}function Vb(a,b){if(!lb(a))throw new F(44);var c=M(b,{parent:!0}).node;if(!c)throw new F(44);b=jb(b);var d=Nb(c,b);if(d)throw new F(d);if(!c.cc.symlink)throw new F(63);return c.cc.symlink(c,b,a)}
function Wb(a){var b=M(a,{parent:!0}).node,c=jb(a),d=xb(b,c),e=Ob(b,c,!1);if(e)throw new F(e);if(!b.cc.unlink)throw new F(63);if(d.uc)throw new F(10);try{L.willDeletePath&&L.willDeletePath(a)}catch(f){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+f.message)}b.cc.unlink(b,c);Ib(d);try{if(L.onDeletePath)L.onDeletePath(a)}catch(f){console.log("FS.trackingDelegate['onDeletePath']('"+a+"') threw an exception: "+f.message)}}
function Fb(a){a=M(a).node;if(!a)throw new F(44);if(!a.cc.readlink)throw new F(28);return lb(N(a.parent),a.cc.readlink(a))}function Xb(a,b){var c;"string"===typeof a?c=M(a,{sc:!0}).node:c=a;if(!c.cc.ic)throw new F(63);c.cc.ic(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Yb(a,b,c,d){if(""===a)throw new F(44);if("string"===typeof b){var e=Lb[b];if("undefined"===typeof e)throw Error("Unknown file open mode: "+b);b=e}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var f=a;else{a=E(a);try{f=M(a,{sc:!(b&131072)}).node}catch(n){}}e=!1;if(b&64)if(f){if(b&128)throw new F(20);}else f=Tb(a,c,0),e=!0;if(!f)throw new F(44);8192===(f.mode&61440)&&(b&=-513);if(b&65536&&!H(f.mode))throw new F(54);if(!e&&(c=f?40960===(f.mode&61440)?32:H(f.mode)&&
("r"!==Mb(b)||b&512)?31:Jb(f,Mb(b)):44))throw new F(c);if(b&512){c=f;var k;"string"===typeof c?k=M(c,{sc:!0}).node:k=c;if(!k.cc.ic)throw new F(63);if(H(k.mode))throw new F(31);if(32768!==(k.mode&61440))throw new F(28);if(c=Jb(k,"w"))throw new F(c);k.cc.ic(k,{size:0,timestamp:Date.now()})}b&=-641;d=Qb({node:f,path:N(f),flags:b,seekable:!0,position:0,dc:f.dc,od:[],error:!1},d);d.dc.open&&d.dc.open(d);!g.logReadFiles||b&1||(Zb||(Zb={}),a in Zb||(Zb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{L.onOpenFile&&(f=0,1!==(b&2097155)&&(f|=1),0!==(b&2097155)&&(f|=2),L.onOpenFile(a,f))}catch(n){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+n.message)}return d}function $b(a){if(null===a.fd)throw new F(8);a.oc&&(a.oc=null);try{a.dc.close&&a.dc.close(a)}catch(b){throw b;}finally{Ab[a.fd]=null}a.fd=null}
function ac(a,b,c){if(null===a.fd)throw new F(8);if(!a.seekable||!a.dc.pc)throw new F(70);if(0!=c&&1!=c&&2!=c)throw new F(28);a.position=a.dc.pc(a,b,c);a.od=[];return a.position}
function bc(a,b,c,d,e,f){if(0>d||0>e)throw new F(28);if(null===a.fd)throw new F(8);if(0===(a.flags&2097155))throw new F(8);if(H(a.node.mode))throw new F(31);if(!a.dc.write)throw new F(28);a.flags&1024&&ac(a,0,2);var k="undefined"!==typeof e;if(!k)e=a.position;else if(!a.seekable)throw new F(70);b=a.dc.write(a,b,c,d,e,f);k||(a.position+=b);try{if(a.path&&L.onWriteToFile)L.onWriteToFile(a.path)}catch(n){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+n.message)}return b}
function cc(){F||(F=function(a,b){this.node=b;this.nd=function(a){this.fc=a};this.nd(a);this.message="FS error"},F.prototype=Error(),F.prototype.constructor=F,[44].forEach(function(a){wb[a]=new F(a);wb[a].stack="<generic error, no stack>"}))}var dc;function ec(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function fc(a,b,c,d){a=E(("string"===typeof a?a:N(a))+"/"+b);return O(a,ec(c,d))}
function hc(a,b){a="string"===typeof a?a:N(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=E(a+"/"+c);try{O(d)}catch(e){}a=d}}return d}function ic(a,b,c,d){a=E(("string"===typeof a?a:N(a))+"/"+b);c=ec(c,d);return Tb(a,(void 0!==c?c:438)&4095|32768,0)}
function jc(a,b,c,d,e,f){a=b?E(("string"===typeof a?a:N(a))+"/"+b):a;d=ec(d,e);e=Tb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var k=c.length;b<k;++b)a[b]=c.charCodeAt(b);c=a}Xb(e,d|146);a=Yb(e,"w");bc(a,c,0,c.length,0,f);$b(a);Xb(e,d)}return e}
function P(a,b,c,d){a=E(("string"===typeof a?a:N(a))+"/"+b);b=ec(!!c,!!d);P.Rc||(P.Rc=64);var e=P.Rc++<<8|0;pb(e,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,e){for(var f=0,k=0;k<e;k++){try{var n=c()}catch(D){throw new F(29);}if(void 0===n&&0===f)throw new F(6);if(null===n||void 0===n)break;f++;b[d+k]=n}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,e){for(var f=0;f<e;f++)try{d(b[c+f])}catch(t){throw new F(29);}e&&(a.node.timestamp=
Date.now());return f}});return Ub(a,b,e)}function kc(a,b,c){a=E(("string"===typeof a?a:N(a))+"/"+b);return Vb(c,a)}
function lc(a){if(a.ed||a.gd||a.link||a.bc)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(la)try{a.bc=rb(la(a.url)),a.ec=a.bc.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||kb(29);return b}
function mc(a,b,c,d,e){function f(){this.Ec=!1;this.Ac=[]}f.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Qc(a/this.chunkSize|0)[b]}};f.prototype.md=function(a){this.Qc=a};f.prototype.Jc=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,e=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var f=1048576;e||(f=b);var k=this;k.md(function(a){var d=a*f,e=(a+1)*f-1;e=Math.min(e,b-1);if("undefined"===typeof k.Ac[a]){var n=k.Ac;if(d>e)throw Error("invalid range ("+d+", "+e+") or no bytes requested!");if(e>b-1)throw Error("only "+b+" bytes available! programmer error!");var p=new XMLHttpRequest;p.open("GET",c,!1);b!==f&&p.setRequestHeader("Range","bytes="+d+"-"+e);"undefined"!=typeof Uint8Array&&(p.responseType="arraybuffer");
p.overrideMimeType&&p.overrideMimeType("text/plain; charset=x-user-defined");p.send(null);if(!(200<=p.status&&300>p.status||304===p.status))throw Error("Couldn't load "+c+". Status: "+p.status);d=void 0!==p.response?new Uint8Array(p.response||[]):rb(p.responseText||"");n[a]=d}if("undefined"===typeof k.Ac[a])throw Error("doXHR failed!");return k.Ac[a]});if(a||!b)f=b=1,f=b=this.Qc(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Xc=b;this.Wc=
f;this.Ec=!0};if("undefined"!==typeof XMLHttpRequest){if(!ha)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var k=new f;Object.defineProperties(k,{length:{get:function(){this.Ec||this.Jc();return this.Xc}},chunkSize:{get:function(){this.Ec||this.Jc();return this.Wc}}});var n=void 0}else n=c,k=void 0;var p=ic(a,b,d,e);k?p.bc=k:n&&(p.bc=null,p.url=n);Object.defineProperties(p,{ec:{get:function(){return this.bc.length}}});var r=
{};Object.keys(p.dc).forEach(function(a){var b=p.dc[a];r[a]=function(){if(!lc(p))throw new F(29);return b.apply(null,arguments)}});r.read=function(a,b,c,d,e){if(!lc(p))throw new F(29);a=a.node.bc;if(e>=a.length)return 0;d=Math.min(a.length-e,d);if(a.slice)for(var f=0;f<d;f++)b[c+f]=a[e+f];else for(f=0;f<d;f++)b[c+f]=a.get(e+f);return d};p.dc=r;return p}
function nc(a,b,c,d,e,f,k,n,p,r){function t(c){function t(c){r&&r();n||jc(a,b,c,d,e,p);f&&f();ab(D)}var I=!1;g.preloadPlugins.forEach(function(a){!I&&a.canHandle(J)&&(a.handle(c,J,t,function(){k&&k();ab(D)}),I=!0)});I||t(c)}(void 0).xd();var J=b?lb(E(a+"/"+b)):a,D="cp "+J;$a(D);"string"==typeof c?(void 0).sd(c,function(a){t(a)},k):t(c)}var Q={},Kb,Rb,Zb;
function oc(a,b){try{var c=M(a,{sc:!0}).node;if(!c)throw new F(44);if(!c.cc.jc)throw new F(63);var d=c.cc.jc(c)}catch(e){if(e&&e.node&&E(a)!==E(N(e.node)))return-54;throw e;}x[b>>2]=d.dev;x[b+4>>2]=0;x[b+8>>2]=d.ino;x[b+12>>2]=d.mode;x[b+16>>2]=d.nlink;x[b+20>>2]=d.uid;x[b+24>>2]=d.gid;x[b+28>>2]=d.rdev;x[b+32>>2]=0;C=[d.size>>>0,(B=d.size,1<=+Ta(B)?0<B?(Wa(+Va(B/4294967296),4294967295)|0)>>>0:~~+Ua((B-+(~~B>>>0))/4294967296)>>>0:0)];x[b+40>>2]=C[0];x[b+44>>2]=C[1];x[b+48>>2]=4096;x[b+52>>2]=d.blocks;
x[b+56>>2]=d.atime.getTime()/1E3|0;x[b+60>>2]=0;x[b+64>>2]=d.mtime.getTime()/1E3|0;x[b+68>>2]=0;x[b+72>>2]=d.ctime.getTime()/1E3|0;x[b+76>>2]=0;C=[d.ino>>>0,(B=d.ino,1<=+Ta(B)?0<B?(Wa(+Va(B/4294967296),4294967295)|0)>>>0:~~+Ua((B-+(~~B>>>0))/4294967296)>>>0:0)];x[b+80>>2]=C[0];x[b+84>>2]=C[1];return 0}var R=0;function S(){R+=4;return x[R-4>>2]}function T(a){void 0===a&&(a=S());a=Ab[a];if(!a)throw new F(8);return a}var pc=0,qc=0,U=0,rc=0,sc=0,tc=null,uc=null,wc=!1;
function xc(){for(var a=yc.length-1;0<=a;--a)zc(a);yc=[];Ac=[]}var Ac=[];function Bc(){if(Cc&&Dc.nc)for(var a=0;a<Ac.length;++a){var b=Ac[a];Ac.splice(a,1);--a;b.Dd.apply(this,b.rd)}}var Cc=0,Dc=null,yc=[];function Ec(){return-1!==navigator.userAgent.indexOf("MSIE")||0<navigator.appVersion.indexOf("Trident/")}function zc(a){var b=yc[a];b.target.removeEventListener(b.lc,b.$c,b.qc);yc.splice(a,1)}
function Fc(a){function b(b){++Cc;Dc=a;Bc();a.tc(b);Bc();--Cc}if(a.rc)a.$c=b,a.target.addEventListener(a.lc,b,a.qc),yc.push(a),wc||(Pa.push(xc),wc=!0);else for(var c=0;c<yc.length;++c)yc[c].target==a.target&&yc[c].lc==a.lc&&zc(c--)}var Gc=[0,"undefined"!==typeof document?document:0,"undefined"!==typeof window?window:0];
function Hc(a){try{if(!a)return window;"number"===typeof a&&(a=Gc[a]||w(a));return"#window"===a?window:"#document"===a?document:"#screen"===a?screen:"#canvas"===a?g.canvas:"string"===typeof a?document.getElementById(a):a}catch(b){return null}}function Ic(a){"number"===typeof a&&(a=w(a));return a&&"#canvas"!==a?"undefined"!==typeof Jc&&Kc[a]?Kc[a]:Hc(a):"undefined"!==typeof Jc&&Kc.canvas?Kc.canvas:g.canvas}
function Lc(a,b,c,d,e,f){pc||(pc=K(164));a={target:Hc(a),nc:Ec()?!1:!0,lc:f,rc:d,tc:function(a){a=a||event;var c=pc;q(a.key?a.key:"",u,c+0,32);q(a.code?a.code:"",u,c+32,32);x[c+64>>2]=a.location;x[c+68>>2]=a.ctrlKey;x[c+72>>2]=a.shiftKey;x[c+76>>2]=a.altKey;x[c+80>>2]=a.metaKey;x[c+84>>2]=a.repeat;q(a.locale?a.locale:"",u,c+88,32);q(a.char?a.char:"",u,c+120,32);x[c+152>>2]=a.charCode;x[c+156>>2]=a.keyCode;x[c+160>>2]=a.which;Mc(d,e,c,b)&&a.preventDefault()},qc:c};Fc(a)}
function Nc(a,b,c){A[a>>3]=window.performance&&window.performance.now?window.performance.now():Date.now();x[a+8>>2]=b.screenX;x[a+12>>2]=b.screenY;x[a+16>>2]=b.clientX;x[a+20>>2]=b.clientY;x[a+24>>2]=b.ctrlKey;x[a+28>>2]=b.shiftKey;x[a+32>>2]=b.altKey;x[a+36>>2]=b.metaKey;Ga[a+40>>1]=b.button;Ga[a+42>>1]=b.buttons;x[a+44>>2]=b.movementX||b.mozMovementX||b.webkitMovementX||b.screenX-tc;x[a+48>>2]=b.movementY||b.mozMovementY||b.webkitMovementY||b.screenY-uc;if(g.canvas){var d=g.canvas.getBoundingClientRect();
x[a+60>>2]=b.clientX-d.left;x[a+64>>2]=b.clientY-d.top}else x[a+60>>2]=0,x[a+64>>2]=0;c?(d=c.getBoundingClientRect?c.getBoundingClientRect():{left:0,top:0},x[a+52>>2]=b.clientX-d.left,x[a+56>>2]=b.clientY-d.top):(x[a+52>>2]=0,x[a+56>>2]=0);"wheel"!==b.type&&"mousewheel"!==b.type&&(tc=b.screenX,uc=b.screenY)}
function Oc(a,b,c,d,e,f){qc||(qc=K(72));a=Hc(a);c={target:a,nc:"mousemove"!=f&&"mouseenter"!=f&&"mouseleave"!=f,lc:f,rc:d,tc:function(c){c=c||event;Nc(qc,c,a);Mc(d,e,qc,b)&&c.preventDefault()},qc:c};Ec()&&"mousedown"==f&&(c.nc=!1);Fc(c)}
function Pc(a,b,c,d){rc||(rc=K(36));a=Hc(a);Fc({target:a,nc:!1,lc:"resize",rc:d,tc:function(c){c=c||event;if(c.target==a){var e=rc,k=document.body;x[e>>2]=c.detail;x[e+4>>2]=k.clientWidth;x[e+8>>2]=k.clientHeight;x[e+12>>2]=innerWidth;x[e+16>>2]=innerHeight;x[e+20>>2]=outerWidth;x[e+24>>2]=outerHeight;x[e+28>>2]=pageXOffset;x[e+32>>2]=pageYOffset;Mc(d,10,e,b)&&c.preventDefault()}},qc:c})}
function Qc(a,b,c,d,e,f){sc||(sc=K(1684));a=Hc(a);Fc({target:a,nc:"touchstart"==f||"touchend"==f,lc:f,rc:d,tc:function(c){c=c||event;for(var f={},k=0;k<c.touches.length;++k){var r=c.touches[k];r.Kc=!1;f[r.identifier]=r}for(k=0;k<c.changedTouches.length;++k)r=c.changedTouches[k],f[r.identifier]=r,r.Kc=!0;for(k=0;k<c.targetTouches.length;++k)r=c.targetTouches[k],f[r.identifier].kd=!0;var t=r=sc;x[t+4>>2]=c.ctrlKey;x[t+8>>2]=c.shiftKey;x[t+12>>2]=c.altKey;x[t+16>>2]=c.metaKey;t+=20;var J=g.canvas?g.canvas.getBoundingClientRect():
void 0,D=a.getBoundingClientRect?a.getBoundingClientRect():{left:0,top:0},I=0;for(k in f){var z=f[k];x[t>>2]=z.identifier;x[t+4>>2]=z.screenX;x[t+8>>2]=z.screenY;x[t+12>>2]=z.clientX;x[t+16>>2]=z.clientY;x[t+20>>2]=z.pageX;x[t+24>>2]=z.pageY;x[t+28>>2]=z.Kc;x[t+32>>2]=z.kd;J?(x[t+44>>2]=z.clientX-J.left,x[t+48>>2]=z.clientY-J.top):(x[t+44>>2]=0,x[t+48>>2]=0);x[t+36>>2]=z.clientX-D.left;x[t+40>>2]=z.clientY-D.top;t+=52;if(32<=++I)break}x[r>>2]=I;Mc(d,e,r,b)&&c.preventDefault()},qc:c})}
function Rc(a,b,c,d,e,f){a||(a=g.canvas);a={target:Hc(a),nc:!1,lc:f,rc:d,tc:function(a){a=a||event;Mc(d,e,0,b)&&a.preventDefault()},qc:c};Fc(a)}
function Sc(a,b,c,d,e){function f(c){c=c||event;Nc(U,c,a);A[U+72>>3]=c.wheelDeltaX||0;A[U+80>>3]=-(c.wheelDeltaY||c.wheelDelta);A[U+88>>3]=0;x[U+96>>2]=0;Mc(d,9,U,b)&&c.preventDefault()}function k(c){c=c||event;var e=U;Nc(e,c,a);A[e+72>>3]=c.deltaX;A[e+80>>3]=c.deltaY;A[e+88>>3]=c.deltaZ;x[e+96>>2]=c.deltaMode;Mc(d,9,e,b)&&c.preventDefault()}U||(U=K(104));Fc({target:a,nc:!0,lc:e,rc:d,tc:"wheel"==e?k:f,qc:c})}
var Tc=["default","low-power","high-performance"],Uc=1,Vc=0,Wc=[],V=[],Xc=[],Yc=[],Zc=[],W=[],X=[],$c={},ad=null,Kc={},bd={},cd={};function Y(a){Vc||(Vc=a)}function dd(a){for(var b=Uc++,c=a.length;c<b;c++)a[c]=null;return b}var ed=null,fd=[0];
function gd(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(a,d){b.vertexAttribDivisorANGLE(a,d)},a.drawArraysInstanced=function(a,d,e,f){b.drawArraysInstancedANGLE(a,d,e,f)},a.drawElementsInstanced=function(a,d,e,f,k){b.drawElementsInstancedANGLE(a,d,e,f,k)})}
function hd(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(a){b.deleteVertexArrayOES(a)},a.bindVertexArray=function(a){b.bindVertexArrayOES(a)},a.isVertexArray=function(a){return b.isVertexArrayOES(a)})}function id(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(a,d){b.drawBuffersWEBGL(a,d)})}
function jd(a){a||(a=ad);if(!a.cd){a.cd=!0;var b=a.Cc;2>a.version&&(gd(b),hd(b),id(b));b.ud=b.getExtension("EXT_disjoint_timer_query");var c="OES_texture_float OES_texture_half_float OES_standard_derivatives OES_vertex_array_object WEBGL_compressed_texture_s3tc WEBGL_depth_texture OES_element_index_uint EXT_texture_filter_anisotropic EXT_frag_depth WEBGL_draw_buffers ANGLE_instanced_arrays OES_texture_float_linear OES_texture_half_float_linear EXT_blend_minmax EXT_shader_texture_lod WEBGL_compressed_texture_pvrtc EXT_color_buffer_half_float WEBGL_color_buffer_float EXT_sRGB WEBGL_compressed_texture_etc1 EXT_disjoint_timer_query WEBGL_compressed_texture_etc WEBGL_compressed_texture_astc EXT_color_buffer_float WEBGL_compressed_texture_s3tc_srgb EXT_disjoint_timer_query_webgl2 WEBKIT_WEBGL_compressed_texture_pvrtc".split(" ");
(b.getSupportedExtensions()||[]).forEach(function(a){-1!=c.indexOf(a)&&b.getExtension(a)})}}var Jc={},kd,ld;function md(a,b,c,d){for(var e=0;e<a;e++){var f=Z[c](),k=f&&dd(d);f?(f.name=k,d[k]=f):Y(1282);x[b+4*e>>2]=k}}
function nd(a,b){if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 36345:c=0;break;case 34466:var d=Z.getParameter(34467);c=d?d.length:0}if(void 0===c)switch(d=Z.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":Y(1280);return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:c=0;break;default:Y(1280);return}else{if(d instanceof Float32Array||d instanceof Uint32Array||
d instanceof Int32Array||d instanceof Array){for(a=0;a<d.length;++a)x[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){Y(1280);m("GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter("+a+")! (error: "+e+")");return}}break;default:Y(1280);m("GL_INVALID_ENUM in glGet0v: Native code calling glGet0v("+a+") and it returns "+d+" of type "+typeof d+"!");return}x[b>>2]=c}else Y(1281)}function od(a){var b=Da(a)+1,c=K(b);q(a,u,c,b);return c}
function pd(a,b,c,d,e){a-=5120;a=1==a?u:4==a?x:6==a?y:5==a||28922==a?Ia:Ha;var f=31-Math.clz32(a.BYTES_PER_ELEMENT);return a.subarray(e>>f,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<f)+4-1&-4)>>f)}cc();Db=Array(4096);Sb(G,"/");O("/tmp");O("/home");O("/home/web_user");
(function(){O("/dev");pb(259,{read:function(){return 0},write:function(a,b,c,k){return k}});Ub("/dev/null",259);ob(1280,sb);ob(1536,tb);Ub("/dev/tty",1280);Ub("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(ia)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){l("random_device")});P("/dev","random",b);P("/dev","urandom",b);
O("/dev/shm");O("/dev/shm/tmp")})();O("/proc");O("/proc/self");O("/proc/self/fd");Sb({mc:function(){var a=vb("/proc/self","fd",16895,73);a.cc={lookup:function(a,c){var b=Ab[+c];if(!b)throw new F(8);a={parent:null,mc:{Tc:"fake"},cc:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");g.FS_createFolder=fc;g.FS_createPath=hc;g.FS_createDataFile=jc;g.FS_createPreloadedFile=nc;g.FS_createLazyFile=mc;g.FS_createLink=kc;g.FS_createDevice=P;g.FS_unlink=Wb;var Z;ed=new Float32Array(256);
for(var qd=0;256>qd;qd++)fd[qd]=ed.subarray(0,qd+1);function rb(a){var b=Array(Da(a)+1);a=q(a,b,0,b.length);b.length=a;return b}
var vd={fb:function(){},jb:function(a,b){R=b;try{var c=w(S());Wb(c);return 0}catch(d){return"undefined"!==typeof Q&&d instanceof F||l(d),-d.fc}},db:function(a,b){R=b;try{var c=w(S()),d=M(c,{sc:!0});if(null===d.node)throw new F(44);if(!H(d.node.mode))throw new F(54);var e=Jb(d.node,"x");if(e)throw new F(e);mb=d.path;return 0}catch(f){return"undefined"!==typeof Q&&f instanceof F||l(f),-f.fc}},kb:function(a,b){R=b;try{var c=w(S()),d=S();return oc(c,d)}catch(e){return"undefined"!==typeof Q&&e instanceof
F||l(e),-e.fc}},lb:function(a,b){R=b;try{var c=T(),d=S();return oc(c.path,d)}catch(e){return"undefined"!==typeof Q&&e instanceof F||l(e),-e.fc}},cb:function(a,b){R=b;try{var c=T(),d=S(),e=S();if(!c.oc){var f=M(c.path,{sc:!0}).node;if(!f.cc.readdir)throw new F(54);var k=f.cc.readdir(f);c.oc=k}a=0;for(var n=ac(c,0,1),p=Math.floor(n/280);p<c.oc.length&&a+280<=e;){var r=c.oc[p];if("."===r[0]){var t=1;var J=4}else{var D=xb(c.node,r);t=D.id;J=8192===(D.mode&61440)?2:H(D.mode)?4:40960===(D.mode&61440)?10:
8}C=[t>>>0,(B=t,1<=+Ta(B)?0<B?(Wa(+Va(B/4294967296),4294967295)|0)>>>0:~~+Ua((B-+(~~B>>>0))/4294967296)>>>0:0)];x[d+a>>2]=C[0];x[d+a+4>>2]=C[1];C=[280*(p+1)>>>0,(B=280*(p+1),1<=+Ta(B)?0<B?(Wa(+Va(B/4294967296),4294967295)|0)>>>0:~~+Ua((B-+(~~B>>>0))/4294967296)>>>0:0)];x[d+a+8>>2]=C[0];x[d+a+12>>2]=C[1];Ga[d+a+16>>1]=280;v[d+a+18>>0]=J;q(r,u,d+a+19,256);a+=280;p+=1}ac(c,280*p,0);return a}catch(I){return"undefined"!==typeof Q&&I instanceof F||l(I),-I.fc}},_:function(a,b){R=b;try{var c=T();switch(S()){case 0:var d=
S();return 0>d?-28:Yb(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=S(),c.flags|=d,0;case 12:return d=S(),Ga[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-28;case 9:return kb(28),-1;default:return-28}}catch(e){return"undefined"!==typeof Q&&e instanceof F||l(e),-e.fc}},mb:function(a,b){R=b;try{var c=w(S()),d=S();a=c;a=E(a);"/"===a[a.length-1]&&(a=a.substr(0,a.length-1));O(a,d);return 0}catch(e){return"undefined"!==typeof Q&&e instanceof F||l(e),-e.fc}},
aa:function(a,b){R=b;try{var c=w(S()),d=M(c,{parent:!0}).node,e=jb(c),f=xb(d,e),k=Ob(d,e,!0);if(k)throw new F(k);if(!d.cc.rmdir)throw new F(63);if(f.uc)throw new F(10);try{L.willDeletePath&&L.willDeletePath(c)}catch(n){console.log("FS.trackingDelegate['willDeletePath']('"+c+"') threw an exception: "+n.message)}d.cc.rmdir(d,e);Ib(f);try{if(L.onDeletePath)L.onDeletePath(c)}catch(n){console.log("FS.trackingDelegate['onDeletePath']('"+c+"') threw an exception: "+n.message)}return 0}catch(n){return"undefined"!==
typeof Q&&n instanceof F||l(n),-n.fc}},$:function(a,b){R=b;try{var c=w(S()),d=S(),e=S();return Yb(c,d,e).fd}catch(f){return"undefined"!==typeof Q&&f instanceof F||l(f),-f.fc}},ib:function(a,b){R=b;try{var c=T(),d=S();switch(d){case 21509:case 21505:return c.tty?0:-59;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-59;case 21519:if(!c.tty)return-59;var e=S();return x[e>>2]=0;case 21520:return c.tty?-28:-59;case 21531:a=e=S();if(!c.dc.dd)throw new F(59);return c.dc.dd(c,
d,a);case 21523:return c.tty?0:-59;case 21524:return c.tty?0:-59;default:l("bad ioctl syscall "+d)}}catch(f){return"undefined"!==typeof Q&&f instanceof F||l(f),-f.fc}},B:function(){},vb:function(){console.log("fs.h: registering Module['ccall']");g.ccall=xa},wb:function(a){var b=w(a),c=new XMLHttpRequest;c.open("GET",b);c.responseType="arraybuffer";c.onload=function(){var a=new Uint8Array(c.response);xa("emsc_load_data","int",["string","array","number"],[b,a,a.length])};c.send()},R:function(){return devicePixelRatio||
1},Z:function(a,b,c){a=a?Hc(a):g.canvas;if(!a)return-4;a.getBoundingClientRect?(a=a.getBoundingClientRect(),A[b>>3]=a.right-a.left,A[c>>3]=a.bottom-a.top):(A[b>>3]=a.clientWidth,A[c>>3]=a.clientHeight);return 0},_a:function(a,b,c){u.set(u.subarray(b,b+c),a)},Ka:function(a,b){function c(d){rd(a,d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},$a:function(a){if(2147418112<a)return!1;for(var b=Math.max(v.length,16777216);b<a;)536870912>=b?b=Fa(2*b):b=Math.min(Fa((3*b+2147483648)/4),2147418112);
a:{try{ta.grow(b-buffer.byteLength+65535>>16);Ja(ta.buffer);var c=1;break a}catch(d){}c=void 0}return c?!0:!1},P:function(a,b,c){a=Ic(a);if(!a)return-4;a.width=b;a.height=c;return 0},Ua:function(a,b,c,d){Lc(a,b,c,d,2,"keydown");return 0},Sa:function(a,b,c,d){Lc(a,b,c,d,1,"keypress");return 0},Ta:function(a,b,c,d){Lc(a,b,c,d,3,"keyup");return 0},nb:function(a,b,c,d){Oc(a,b,c,d,5,"mousedown");return 0},Xa:function(a,b,c,d){Oc(a,b,c,d,33,"mouseenter");return 0},Wa:function(a,b,c,d){Oc(a,b,c,d,34,"mouseleave");
return 0},Za:function(a,b,c,d){Oc(a,b,c,d,8,"mousemove");return 0},hb:function(a,b,c,d){Oc(a,b,c,d,6,"mouseup");return 0},Ea:function(a,b,c,d){Pc(a,b,c,d);return 0},Na:function(a,b,c,d){Qc(a,b,c,d,25,"touchcancel");return 0},Oa:function(a,b,c,d){Qc(a,b,c,d,23,"touchend");return 0},Pa:function(a,b,c,d){Qc(a,b,c,d,24,"touchmove");return 0},Qa:function(a,b,c,d){Qc(a,b,c,d,22,"touchstart");return 0},Ma:function(a,b,c,d){Rc(a,b,c,d,31,"webglcontextlost");return 0},La:function(a,b,c,d){Rc(a,b,c,d,32,"webglcontextrestored");
return 0},Va:function(a,b,c,d){a=Hc(a);return"undefined"!==typeof a.onwheel?(Sc(a,b,c,d,"wheel"),0):"undefined"!==typeof a.onmousewheel?(Sc(a,b,c,d,"mousewheel"),0):-1},G:function(a,b){var c={};b>>=2;c.alpha=!!x[b];c.depth=!!x[b+1];c.stencil=!!x[b+2];c.antialias=!!x[b+3];c.premultipliedAlpha=!!x[b+4];c.preserveDrawingBuffer=!!x[b+5];c.powerPreference=Tc[x[b+6]];c.failIfMajorPerformanceCaveat=!!x[b+7];c.hd=x[b+8];c.yd=x[b+9];c.Mc=x[b+10];c.ad=x[b+11];c.Ad=x[b+12];c.Cd=x[b+13];a=Ic(a);if(!a||c.ad)c=
0;else if(a=a.getContext("webgl",c)||a.getContext("experimental-webgl",c)){b=K(8);var d={handle:b,attributes:c,version:c.hd,Cc:a};a.canvas&&(a.canvas.pd=d);$c[b]=d;("undefined"===typeof c.Mc||c.Mc)&&jd(d);c=b}else c=0;return c},ub:function(a,b){a=$c[a];b=w(b);0==b.indexOf("GL_")&&(b=b.substr(3));"ANGLE_instanced_arrays"==b?gd(Z):"OES_vertex_array_object"==b?hd(Z):"WEBGL_draw_buffers"==b&&id(Z);return!!a.Cc.getExtension(b)},ua:function(a){a>>=2;for(var b=0;14>b;++b)x[a+b]=0;x[a]=x[a+1]=x[a+3]=x[a+
4]=x[a+8]=x[a+10]=1},la:function(a){ad=$c[a];g.td=Z=ad&&ad.Cc;return!a||Z?0:-5},s:function(a){try{var b=T(a);$b(b);return 0}catch(c){return"undefined"!==typeof Q&&c instanceof F||l(c),c.fc}},bb:function(a,b){try{var c=T(a);v[b>>0]=c.tty?2:H(c.mode)?3:40960===(c.mode&61440)?7:4;return 0}catch(d){return"undefined"!==typeof Q&&d instanceof F||l(d),d.fc}},eb:function(a,b,c,d){try{a:{for(var e=T(a),f=a=0;f<c;f++){var k=x[b+(8*f+4)>>2],n=e,p=x[b+8*f>>2],r=k,t=void 0,J=v;if(0>r||0>t)throw new F(28);if(null===
n.fd)throw new F(8);if(1===(n.flags&2097155))throw new F(8);if(H(n.node.mode))throw new F(31);if(!n.dc.read)throw new F(28);var D="undefined"!==typeof t;if(!D)t=n.position;else if(!n.seekable)throw new F(70);var I=n.dc.read(n,J,p,r,t);D||(n.position+=I);var z=I;if(0>z){var vc=-1;break a}a+=z;if(z<k)break}vc=a}x[d>>2]=vc;return 0}catch(Bb){return"undefined"!==typeof Q&&Bb instanceof F||l(Bb),Bb.fc}},Ya:function(a,b,c,d,e){try{var f=T(a);a=4294967296*c+(b>>>0);if(-9007199254740992>=a||9007199254740992<=
a)return-61;ac(f,a,d);C=[f.position>>>0,(B=f.position,1<=+Ta(B)?0<B?(Wa(+Va(B/4294967296),4294967295)|0)>>>0:~~+Ua((B-+(~~B>>>0))/4294967296)>>>0:0)];x[e>>2]=C[0];x[e+4>>2]=C[1];f.oc&&0===a&&0===d&&(f.oc=null);return 0}catch(k){return"undefined"!==typeof Q&&k instanceof F||l(k),k.fc}},gb:function(a,b,c,d){try{a:{for(var e=T(a),f=a=0;f<c;f++){var k=bc(e,v,x[b+8*f>>2],x[b+(8*f+4)>>2],void 0);if(0>k){var n=-1;break a}a+=k}n=a}x[d>>2]=n;return 0}catch(p){return"undefined"!==typeof Q&&p instanceof F||
l(p),p.fc}},g:function(a){Z.activeTexture(a)},S:function(a,b){Z.attachShader(V[a],X[b])},b:function(a,b){Z.bindBuffer(a,Wc[b])},f:function(a,b){Z.bindFramebuffer(a,Xc[b])},Da:function(a,b){Z.bindRenderbuffer(a,Yc[b])},a:function(a,b){Z.bindTexture(a,Zc[b])},I:function(a,b,c,d){Z.blendColor(a,b,c,d)},J:function(a,b){Z.blendEquationSeparate(a,b)},K:function(a,b,c,d){Z.blendFuncSeparate(a,b,c,d)},V:function(a,b,c,d){Z.bufferData(a,c?u.subarray(c,c+b):b,d)},q:function(a,b,c,d){Z.bufferSubData(a,b,u.subarray(d,
d+c))},m:function(a){return Z.checkFramebufferStatus(a)},sa:function(a){Z.clear(a)},wa:function(a,b,c,d){Z.clearColor(a,b,c,d)},va:function(a){Z.clearDepth(a)},ta:function(a){Z.clearStencil(a)},z:function(a,b,c,d){Z.colorMask(!!a,!!b,!!c,!!d)},pb:function(a){Z.compileShader(X[a])},U:function(a,b,c,d,e,f,k,n){Z.compressedTexImage2D(a,b,c,d,e,f,n?u.subarray(n,n+k):null)},Aa:function(){var a=dd(V),b=Z.createProgram();b.name=a;V[a]=b;return a},rb:function(a){var b=dd(X);X[b]=Z.createShader(a);return b},
H:function(a){Z.cullFace(a)},Ga:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Wc[d];e&&(Z.deleteBuffer(e),e.name=0,Wc[d]=null,d==kd&&(kd=0),d==ld&&(ld=0))}},j:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Xc[d];e&&(Z.deleteFramebuffer(e),e.name=0,Xc[d]=null)}},X:function(a){if(a){var b=V[a];b?(Z.deleteProgram(b),b.name=0,V[a]=null,bd[a]=null):Y(1281)}},r:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Yc[d];e&&(Z.deleteRenderbuffer(e),e.name=0,Yc[d]=null)}},A:function(a){if(a){var b=
X[a];b?(Z.deleteShader(b),X[a]=null):Y(1281)}},Y:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Zc[d];e&&(Z.deleteTexture(e),e.name=0,Zc[d]=null)}},x:function(a){Z.depthFunc(a)},y:function(a){Z.depthMask(!!a)},d:function(a){Z.disable(a)},C:function(a){Z.disableVertexAttribArray(a)},ha:function(a,b,c){Z.drawArrays(a,b,c)},ia:function(a,b,c,d){Z.drawElements(a,b,c,d)},e:function(a){Z.enable(a)},pa:function(a){Z.enableVertexAttribArray(a)},k:function(a,b,c,d){Z.framebufferRenderbuffer(a,b,c,
Yc[d])},c:function(a,b,c,d,e){Z.framebufferTexture2D(a,b,c,Zc[d],e)},F:function(a){Z.frontFace(a)},W:function(a,b){md(a,b,"createBuffer",Wc)},n:function(a,b){md(a,b,"createFramebuffer",Xc)},Fa:function(a,b){md(a,b,"createRenderbuffer",Yc)},Ba:function(a,b){md(a,b,"createTexture",Zc)},xa:function(a,b){return Z.getAttribLocation(V[a],w(b))},i:function(a,b){nd(a,b)},ya:function(a,b,c,d){a=Z.getProgramInfoLog(V[a]);null===a&&(a="(unknown error)");b=0<b&&d?q(a,u,d,b):0;c&&(x[c>>2]=b)},Q:function(a,b,c){if(c)if(a>=
Uc)Y(1281);else{var d=bd[a];if(d)if(35716==b)a=Z.getProgramInfoLog(V[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b)x[c>>2]=d.Fc;else if(35722==b){if(-1==d.yc){a=V[a];var e=Z.getProgramParameter(a,35721);for(b=d.yc=0;b<e;++b)d.yc=Math.max(d.yc,Z.getActiveAttrib(a,b).name.length+1)}x[c>>2]=d.yc}else if(35381==b){if(-1==d.zc)for(a=V[a],e=Z.getProgramParameter(a,35382),b=d.zc=0;b<e;++b)d.zc=Math.max(d.zc,Z.getActiveUniformBlockName(a,b).length+1);x[c>>2]=d.zc}else x[c>>2]=Z.getProgramParameter(V[a],
b);else Y(1282)}else Y(1281)},ob:function(a,b,c,d){a=Z.getShaderInfoLog(X[a]);null===a&&(a="(unknown error)");b=0<b&&d?q(a,u,d,b):0;c&&(x[c>>2]=b)},ca:function(a,b,c){c?35716==b?(a=Z.getShaderInfoLog(X[a]),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1):35720==b?(a=Z.getShaderSource(X[a]),x[c>>2]=null===a||0==a.length?0:a.length+1):x[c>>2]=Z.getShaderParameter(X[a],b):Y(1281)},Ha:function(a){if(cd[a])return cd[a];switch(a){case 7939:var b=Z.getSupportedExtensions()||[];b=b.concat(b.map(function(a){return"GL_"+
a}));b=od(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=Z.getParameter(a))||Y(1280);b=od(b);break;case 7938:b=od("OpenGL ES 2.0 ("+Z.getParameter(Z.VERSION)+")");break;case 35724:b=Z.getParameter(Z.SHADING_LANGUAGE_VERSION);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=od(b);break;default:return Y(1280),0}return cd[a]=b},l:function(a,b){b=w(b);var c=0;if("]"==b[b.length-1]){var d=b.lastIndexOf("[");
c="]"!=b[d+1]?parseInt(b.slice(d+1)):0;b=b.slice(0,d)}return(a=bd[a]&&bd[a].Vc[b])&&0<=c&&c<a[0]?a[1]+c:-1},za:function(a){Z.linkProgram(V[a]);var b=V[a];a=bd[a]={Vc:{},Fc:0,yc:-1,zc:-1};for(var c=a.Vc,d=Z.getProgramParameter(b,35718),e=0;e<d;++e){var f=Z.getActiveUniform(b,e),k=f.name;a.Fc=Math.max(a.Fc,k.length+1);"]"==k.slice(-1)&&(k=k.slice(0,k.lastIndexOf("[")));var n=Z.getUniformLocation(b,k);if(n){var p=dd(W);c[k]=[f.size,p];W[p]=n;for(var r=1;r<f.size;++r)n=Z.getUniformLocation(b,k+"["+r+
"]"),p=dd(W),W[p]=n}}},E:function(a,b){Z.polygonOffset(a,b)},Ca:function(a,b,c,d){Z.renderbufferStorage(a,b,c,d)},N:function(a,b,c,d){Z.scissor(a,b,c,d)},qb:function(a,b,c,d){for(var e="",f=0;f<b;++f){var k=d?x[d+4*f>>2]:-1;e+=w(x[c+4*f>>2],0>k?void 0:k)}Z.shaderSource(X[a],e)},ga:function(a,b,c){Z.stencilFunc(a,b,c)},M:function(a,b,c,d){Z.stencilFuncSeparate(a,b,c,d)},w:function(a){Z.stencilMask(a)},fa:function(a,b,c){Z.stencilOp(a,b,c)},L:function(a,b,c,d){Z.stencilOpSeparate(a,b,c,d)},T:function(a,
b,c,d,e,f,k,n,p){Z.texImage2D(a,b,c,d,e,f,k,n,p?pd(n,k,d,e,p):null)},h:function(a,b,c){Z.texParameteri(a,b,c)},p:function(a,b,c,d,e,f,k,n,p){var r=null;p&&(r=pd(n,k,e,f,p));Z.texSubImage2D(a,b,c,d,e,f,k,n,r)},oa:function(a,b,c){if(256>=b)for(var d=fd[b-1],e=0;e<b;++e)d[e]=y[c+4*e>>2];else d=y.subarray(c>>2,c+4*b>>2);Z.uniform1fv(W[a],d)},D:function(a,b){Z.uniform1i(W[a],b)},na:function(a,b,c){if(256>=2*b)for(var d=fd[2*b-1],e=0;e<2*b;e+=2)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2];else d=y.subarray(c>>
2,c+8*b>>2);Z.uniform2fv(W[a],d)},ma:function(a,b,c){if(256>=3*b)for(var d=fd[3*b-1],e=0;e<3*b;e+=3)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2];else d=y.subarray(c>>2,c+12*b>>2);Z.uniform3fv(W[a],d)},ka:function(a,b,c){if(256>=4*b)for(var d=fd[4*b-1],e=0;e<4*b;e+=4)d[e]=y[c+4*e>>2],d[e+1]=y[c+(4*e+4)>>2],d[e+2]=y[c+(4*e+8)>>2],d[e+3]=y[c+(4*e+12)>>2];else d=y.subarray(c>>2,c+16*b>>2);Z.uniform4fv(W[a],d)},ja:function(a,b,c,d){if(256>=16*b)for(var e=fd[16*b-1],f=0;f<16*b;f+=16)e[f]=
y[d+4*f>>2],e[f+1]=y[d+(4*f+4)>>2],e[f+2]=y[d+(4*f+8)>>2],e[f+3]=y[d+(4*f+12)>>2],e[f+4]=y[d+(4*f+16)>>2],e[f+5]=y[d+(4*f+20)>>2],e[f+6]=y[d+(4*f+24)>>2],e[f+7]=y[d+(4*f+28)>>2],e[f+8]=y[d+(4*f+32)>>2],e[f+9]=y[d+(4*f+36)>>2],e[f+10]=y[d+(4*f+40)>>2],e[f+11]=y[d+(4*f+44)>>2],e[f+12]=y[d+(4*f+48)>>2],e[f+13]=y[d+(4*f+52)>>2],e[f+14]=y[d+(4*f+56)>>2],e[f+15]=y[d+(4*f+60)>>2];else e=y.subarray(d>>2,d+64*b>>2);Z.uniformMatrix4fv(W[a],!!c,e)},ra:function(a){Z.useProgram(V[a])},ab:function(a,b){Z.vertexAttribDivisor(a,
b)},qa:function(a,b,c,d,e,f){Z.vertexAttribPointer(a,b,c,!!d,e,f)},O:function(a,b,c,d){Z.viewport(a,b,c,d)},memory:ta,v:function(){var a=document.createElement("input");a.type="text";a.id="_sokol_app_input_element";a.autocapitalize="none";a.addEventListener("focusout",function(){sd()});document.body.append(a)},u:function(){document.getElementById("_sokol_app_input_element").focus()},Ja:function(){window.addEventListener("beforeunload",function(a){0!=td()&&(a.preventDefault(),a.returnValue=" ")})},
Ra:function(){window.addEventListener("paste",function(a){a=a.clipboardData.getData("text");xa("_sapp_emsc_onpaste","void",["string"],[a])})},t:function(){document.getElementById("_sokol_app_input_element").blur()},Ia:function(a){a=w(a);var b=document.createElement("textarea");b.setAttribute("autocomplete","off");b.setAttribute("autocorrect","off");b.setAttribute("autocapitalize","off");b.setAttribute("spellcheck","false");b.style.left="-100px";b.style.top="-100px";b.style.height=1;b.style.width=
1;b.value=a;document.body.appendChild(b);b.select();document.execCommand("copy");document.body.removeChild(b)},sb:function(){for(var a=(new URLSearchParams(window.location.search)).entries(),b=a.next();!b.done;b=a.next())xa("_sargs_add_kvp","void",["string","string"],[b.value[0],b.value[1]])},tb:function(){return g.xc?g.xc.bufferSize:0},ea:function(a,b,c){g.hc=null;g.xc=null;"undefined"!==typeof AudioContext?(g.hc=new AudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created AudioContext")):
"undefined"!==typeof webkitAudioContext?(g.hc=new webkitAudioContext({sampleRate:a,latencyHint:"interactive"}),console.log("sokol_audio.h: created webkitAudioContext")):(g.hc=null,console.log("sokol_audio.h: no WebAudio support"));return g.hc?(console.log("sokol_audio.h: sample rate ",g.hc.sampleRate),g.xc=g.hc.createScriptProcessor(c,0,b),g.xc.onaudioprocess=function(a){var b=a.outputBuffer.length,c=ud(b);if(c)for(var d=a.outputBuffer.numberOfChannels,n=0;n<d;n++)for(var p=a.outputBuffer.getChannelData(n),
r=0;r<b;r++)p[r]=y[(c>>2)+(d*r+n)]},g.xc.connect(g.hc.destination),a=function(){g.hc&&"suspended"===g.hc.state&&g.hc.resume()},document.addEventListener("click",a,{once:!0}),document.addEventListener("touchstart",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},da:function(){return g.hc?g.hc.sampleRate:0},ba:function(){return navigator.userAgent.includes("Macintosh")?1:0},o:function(){return performance.now()},table:ua},wd=function(){function a(a){g.asm=a.exports;ab("wasm-instantiate")}
function b(b){a(b.instance)}function c(a){return fb().then(function(a){return WebAssembly.instantiate(a,d)}).then(a,function(a){m("failed to asynchronously prepare wasm: "+a);l(a)})}var d={env:vd,wasi_unstable:vd};$a("wasm-instantiate");if(g.instantiateWasm)try{return g.instantiateWasm(d,a)}catch(e){return m("Module.instantiateWasm callback failed with error: "+e),!1}(function(){if(ra||"function"!==typeof WebAssembly.instantiateStreaming||bb()||"function"!==typeof fetch)return c(b);fetch(cb,{credentials:"same-origin"}).then(function(a){return WebAssembly.instantiateStreaming(a,
d).then(b,function(a){m("wasm streaming compile failed: "+a);m("falling back to ArrayBuffer instantiation");c(b)})})})();return{}}();g.asm=wd;var gb=g.___wasm_call_ctors=function(){return g.asm.xb.apply(null,arguments)};g._emsc_load_data=function(){return g.asm.yb.apply(null,arguments)};g.___em_js__emsc_fs_init=function(){return g.asm.zb.apply(null,arguments)};g.___em_js__emsc_load_file=function(){return g.asm.Ab.apply(null,arguments)};
var sd=g.__sapp_emsc_notify_keyboard_hidden=function(){return g.asm.Bb.apply(null,arguments)};g.___em_js__sapp_js_create_textfield=function(){return g.asm.Cb.apply(null,arguments)};g.___em_js__sapp_js_focus_textfield=function(){return g.asm.Db.apply(null,arguments)};g.___em_js__sapp_js_unfocus_textfield=function(){return g.asm.Eb.apply(null,arguments)};g.__sapp_emsc_onpaste=function(){return g.asm.Fb.apply(null,arguments)};
var td=g.__sapp_html5_get_ask_leave_site=function(){return g.asm.Gb.apply(null,arguments)};g.___em_js__sapp_js_hook_beforeunload=function(){return g.asm.Hb.apply(null,arguments)};g.___em_js__sapp_js_init_clipboard=function(){return g.asm.Ib.apply(null,arguments)};g.___em_js__sapp_js_write_clipboard=function(){return g.asm.Jb.apply(null,arguments)};g._main=function(){return g.asm.Kb.apply(null,arguments)};var K=g._malloc=function(){return g.asm.Lb.apply(null,arguments)};
g._free=function(){return g.asm.Mb.apply(null,arguments)};g.___em_js__stm_js_perfnow=function(){return g.asm.Nb.apply(null,arguments)};var ud=g.__saudio_emsc_pull=function(){return g.asm.Ob.apply(null,arguments)};g.___em_js__saudio_js_init=function(){return g.asm.Pb.apply(null,arguments)};g.___em_js__saudio_js_sample_rate=function(){return g.asm.Qb.apply(null,arguments)};g.___em_js__saudio_js_buffer_frames=function(){return g.asm.Rb.apply(null,arguments)};
g.__sargs_add_kvp=function(){return g.asm.Sb.apply(null,arguments)};g.___em_js__sargs_js_parse_url=function(){return g.asm.Tb.apply(null,arguments)};g.___em_js__simgui_js_is_osx=function(){return g.asm.Ub.apply(null,arguments)};g.___errno_location=function(){return g.asm.Vb.apply(null,arguments)};var za=g.stackSave=function(){return g.asm.Wb.apply(null,arguments)},ya=g.stackAlloc=function(){return g.asm.Xb.apply(null,arguments)},Aa=g.stackRestore=function(){return g.asm.Yb.apply(null,arguments)};
g.dynCall_vi=function(){return g.asm.Zb.apply(null,arguments)};g.dynCall_v=function(){return g.asm._b.apply(null,arguments)};var Mc=g.dynCall_iiii=function(){return g.asm.$b.apply(null,arguments)},rd=g.dynCall_idi=function(){return g.asm.ac.apply(null,arguments)};g.asm=wd;g.getMemory=function(a){if(Ra)var b=K(a);else b=x[1711768],a=b+a+15&-16,a>v.length&&l(),x[1711768]=a;return b};g.addRunDependency=$a;g.removeRunDependency=ab;g.FS_createFolder=fc;g.FS_createPath=hc;g.FS_createDataFile=jc;
g.FS_createPreloadedFile=nc;g.FS_createLazyFile=mc;g.FS_createLink=kc;g.FS_createDevice=P;g.FS_unlink=Wb;g.calledRun=xd;var xd;function pa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Za=function yd(){xd||zd();xd||(Za=yd)};
function zd(a){function b(){if(!xd&&(xd=!0,g.calledRun=!0,!va)){Ra=!0;g.noFSInit||dc||(dc=!0,cc(),g.stdin=g.stdin,g.stdout=g.stdout,g.stderr=g.stderr,g.stdin?P("/dev","stdin",g.stdin):Vb("/dev/tty","/dev/stdin"),g.stdout?P("/dev","stdout",null,g.stdout):Vb("/dev/tty","/dev/stdout"),g.stderr?P("/dev","stderr",null,g.stderr):Vb("/dev/tty1","/dev/stderr"),Yb("/dev/stdin","r"),Yb("/dev/stdout","w"),Yb("/dev/stderr","w"));La(Na);Eb=!1;La(Oa);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(Ad){var b=
a,d=g._main;b=b||[];var e=b.length+1,f=ya(4*(e+1));x[f>>2]=Ea(da);for(var k=1;k<e;k++)x[(f>>2)+k]=Ea(b[k-1]);x[(f>>2)+e]=0;try{var n=d(e,f);if(!sa||0!==n){if(!sa&&(va=!0,g.onExit))g.onExit(n);ea(n,new pa(n))}}catch(p){p instanceof pa||("SimulateInfiniteLoop"==p?sa=!0:((b=p)&&"object"===typeof p&&p.stack&&(b=[p,p.stack]),m("exception thrown: "+b),ea(1,p)))}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)b=g.postRun.shift(),Qa.unshift(b);La(Qa)}}a=
a||ca;if(!(0<Xa)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)Sa();La(Ma);0<Xa||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=zd;if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var Ad=!0;g.noInitialRun&&(Ad=!1);sa=!0;zd();
